name=fish
summary=The fish command line is coloured to match the terminal.
input=launcher-material.theme
output=$XDG_CONFIG_HOME/fish/themes/launcher-material.theme
post_hook=apply.sh
undo_hook=undo.sh
