package com.termux.app.terminal;

import android.app.Application;
import android.os.Build;

import org.junit.Rule;
import org.junit.Test;
import org.junit.rules.TemporaryFolder;
import org.junit.runner.RunWith;
import org.robolectric.RobolectricTestRunner;
import org.robolectric.annotation.Config;

import java.io.File;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.util.Locale;
import java.util.Properties;

import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertFalse;
import static org.junit.Assert.assertNotNull;
import static org.junit.Assert.assertTrue;

/**
 * Shells watch the exported palette by modification time, so rewriting identical content is not
 * free — it makes every open shell re-source on its next prompt.
 */
@RunWith(RobolectricTestRunner.class)
@Config(sdk = Build.VERSION_CODES.P, application = Application.class)
public class MaterialColorExportWriteTest {

    @Rule public TemporaryFolder folder = new TemporaryFolder();

    /** The regression: a line-joining reader drops the trailing newline these files end with. */
    @Test
    public void contentEndingInANewlineStillMatchesItself() throws Exception {
        String content = "# Generated by Termux. Do not edit.\nprimary=#FFB3AE\nsurface=#1A1111\n";
        File file = folder.newFile("material-colors.properties");
        Files.write(file.toPath(), content.getBytes(StandardCharsets.UTF_8));

        assertTrue(MaterialTerminalColorScheme.alreadyOnDisk(file.getAbsolutePath(), content));
    }

    @Test
    public void changedContentDoesNotMatch() throws Exception {
        File file = folder.newFile("material-colors.sh");
        Files.write(file.toPath(), "export A='#000000'\n".getBytes(StandardCharsets.UTF_8));

        assertFalse(MaterialTerminalColorScheme.alreadyOnDisk(file.getAbsolutePath(),
            "export A='#FFFFFF'\n"));
        // Same length, different bytes — a length-only check would call this a match.
        assertFalse(MaterialTerminalColorScheme.alreadyOnDisk(file.getAbsolutePath(),
            "export B='#000000'\n"));
    }

    @Test
    public void aTruncatedOrExtendedFileDoesNotMatch() throws Exception {
        File file = folder.newFile("trunc.properties");
        Files.write(file.toPath(), "a=1\nb=2\n".getBytes(StandardCharsets.UTF_8));

        assertFalse(MaterialTerminalColorScheme.alreadyOnDisk(file.getAbsolutePath(), "a=1\n"));
        assertFalse(MaterialTerminalColorScheme.alreadyOnDisk(file.getAbsolutePath(),
            "a=1\nb=2\nc=3\n"));
    }

    /**
     * Turkish maps {@code i} to a dotted capital I, so a default-locale upper-case turned
     * {@code primary} into {@code PRİMARY} — not a shell identifier, and the file stopped sourcing.
     */
    @Test
    public void shellExportNamesDoNotFollowTheDeviceLocale() {
        Locale original = Locale.getDefault();
        try {
            Locale.setDefault(new Locale("tr", "TR"));
            Properties props = new Properties();
            props.setProperty("primary", "#FFB3AE");
            props.setProperty("terminal_bright_white", "#EEEEEE");

            String exports = MaterialTerminalColorScheme.toShellExports(props);

            assertTrue(exports, exports.contains("export TERMUX_MATERIAL_PRIMARY="));
            assertTrue(exports, exports.contains("export TERMUX_MATERIAL_TERMINAL_BRIGHT_WHITE="));
            assertFalse(exports, exports.contains("PRİMARY"));
        } finally {
            Locale.setDefault(original);
        }
    }

    /**
     * The files are sourced, not read: a truncating write leaves a window in which a starting shell
     * sources half a palette. The rewrite goes through a sibling and a rename, and takes the sibling
     * with it.
     */
    @Test
    public void aRewriteReplacesTheFileInOneStepAndLeavesNothingBehind() throws Exception {
        File file = folder.newFile("material-colors.sh");
        Files.write(file.toPath(), "export A='#000000'\n".getBytes(StandardCharsets.UTF_8));

        MaterialTerminalColorScheme.writeFile(file.getAbsolutePath(), "export A='#FFFFFF'\n");

        assertEquals("export A='#FFFFFF'\n",
            new String(Files.readAllBytes(file.toPath()), StandardCharsets.UTF_8));
        File[] leftovers = folder.getRoot().listFiles((dir, name) -> name.endsWith(".new"));
        assertNotNull(leftovers);
        assertEquals(0, leftovers.length);
    }

    @Test
    public void aMissingFileNeverMatches() {
        assertFalse(MaterialTerminalColorScheme.alreadyOnDisk(
            new File(folder.getRoot(), "absent.properties").getAbsolutePath(), "a=1\n"));
    }
}
