name=Bat file viewer
summary=Bat's syntax highlighting matches your wallpaper.
input=launcher-material.tmTheme
output=$XDG_CONFIG_HOME/bat/themes/launcher-material.tmTheme
post_hook=apply.sh
undo_hook=undo.sh
