name=Yazi file manager
summary=Yazi's file listing matches your wallpaper's colours.
input=flavor.toml
output=$XDG_CONFIG_HOME/yazi/flavors/launcher-material.yazi/flavor.toml
post_hook=apply.sh
undo_hook=undo.sh
