#!/usr/bin/env bash
# Builds app/src/main/assets/tlstore/catalog.tsv from scripts/tlstore/items.tsv.
#
#   scripts/tlstore/build-catalog.sh [path/to/termux-launcher-binaries/SHA256SUMS]
#
# Digests are never hand-written: a launcher: source is hashed from the file in
# this checkout, a binaries: source is looked up in the SHA256SUMS of the
# termux-launcher-binaries checkout passed as the first argument, and a plain
# http(s) source is downloaded once and hashed here (so building needs the
# network when one of those changes). pkg, bundle, fisher and npm-musl items
# carry no digest — apt, fisher and the npm registry's own sha512 are the check
# there. A source whose digest cannot be computed stops the build: an unpinned
# payload must never reach a phone.
#
# A plain URL must name an immutable revision — a tag or a commit — for the same
# reason a launcher: source does.
#
# The serial is YYYYMMDDNN and only ever moves forward; a second build on the
# same day gets NN + 1, because tlstore accepts a refreshed catalog only when
# its serial is higher than the one it already has.
#
# After building, sign it: scripts/tlstore/sign.sh
set -euo pipefail

here="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
repo="$(cd "$here/../.." && pwd)"
items="$here/items.tsv"
out="$repo/app/src/main/assets/tlstore/catalog.tsv"
sums="${1:-}"

[ -f "$items" ] || { echo "missing $items" >&2; exit 1; }

# --- serial ---------------------------------------------------------------
today="$(date +%Y%m%d)"
seq=1
if [ -f "$out" ]; then
    old="$(sed -n 's/^#.*serial=\([0-9][0-9]*\).*$/\1/p' "$out" | head -1)"
    if [ -n "$old" ] && [ "${old:0:8}" = "$today" ]; then
        seq=$((10#${old:8:2} + 1))
    fi
fi
serial="$(printf '%s%02d' "$today" "$seq")"

# --- digests --------------------------------------------------------------
declare -A binary_digest=()
if [ -n "$sums" ]; then
    [ -f "$sums" ] || { echo "no SHA256SUMS at $sums" >&2; exit 1; }
    while read -r digest name; do
        [ -n "${name:-}" ] || continue
        binary_digest["$name"]="$digest"
    done < "$sums"
fi

fetched="$(mktemp -d)"
trap 'rm -rf "$fetched"' EXIT

digest_for() {
    local kind="$1" source="$2" name="$3" path tag asset
    case "$kind" in
        pkg|bundle|fisher|npm-musl) echo "-"; return 0 ;;
    esac
    case "$source" in
        launcher:*)
            path="${source#launcher:}"
            path="${path%@*}"
            [ -f "$repo/$path" ] || { echo "no such file: $path (for $name)" >&2; return 1; }
            sha256sum "$repo/$path" | cut -d' ' -f1
            ;;
        binaries:*)
            tag="${source#binaries:}"
            asset="${tag%@*}"
            if [ -z "$sums" ]; then
                echo "$name needs a SHA256SUMS argument for $asset" >&2
                return 1
            fi
            if [ -z "${binary_digest["$asset-aarch64"]:-}" ]; then
                echo "$asset-aarch64 is not in $sums (for $name)" >&2
                return 1
            fi
            echo "${binary_digest["$asset-aarch64"]}"
            ;;
        http://*|https://*)
            path="$fetched/$name.payload"
            if [ ! -f "$path" ]; then
                if ! curl -fsSL -o "$path" "$source"; then
                    rm -f "$path"
                    echo "$name: could not download $source" >&2
                    return 1
                fi
            fi
            sha256sum "$path" | cut -d' ' -f1
            ;;
        *)
            echo "$name: cannot compute a digest for $source" >&2
            return 1
            ;;
    esac
}

# --- rows -----------------------------------------------------------------
tmp="$(mktemp)"
trap 'rm -f "$tmp"; rm -rf "$fetched"' EXIT

{
    printf '# tlstore catalog\tserial=%s\n' "$serial"
    printf '# generated by scripts/tlstore/build-catalog.sh from scripts/tlstore/items.tsv — do not edit\n'
    printf '# name\tkind\tversion\tprefixes\tsource\tdigest\ttarget\trequires\toptions\tsummary\n'
} > "$tmp"

failed=0
count=0
while IFS=$'\t' read -r name kind version prefixes source target requires options summary || [ -n "${name:-}" ]; do
    [ -n "${name:-}" ] || continue
    case "$name" in \#*) continue ;; esac
    if [ -z "${summary:-}" ]; then
        echo "$name: expected 9 tab-separated columns" >&2
        failed=1
        continue
    fi
    case "$name" in
        [a-z0-9]*) ;;
        *) echo "$name: a name is [a-z0-9][a-z0-9-]*" >&2; failed=1; continue ;;
    esac
    case "$kind" in
        pkg|binary|file|file-once|fisher|npm-musl|bundle) ;;
        *) echo "$name: unknown kind $kind" >&2; failed=1; continue ;;
    esac
    if ! digest="$(digest_for "$kind" "$source" "$name")"; then
        failed=1
        continue
    fi
    printf '%s\t%s\t%s\t%s\t%s\t%s\t%s\t%s\t%s\t%s\n' \
        "$name" "$kind" "$version" "$prefixes" "$source" "$digest" \
        "$target" "$requires" "$options" "$summary" >> "$tmp"
    count=$((count + 1))
done < "$items"

if [ "$failed" != 0 ]; then
    echo "refusing to write $out" >&2
    exit 1
fi

mkdir -p "$(dirname "$out")"
cp "$tmp" "$out"
chmod 644 "$out"
echo "wrote $out — $count items, serial=$serial"
echo "sign it with scripts/tlstore/sign.sh before it ships"
